### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by BenWildeman** [unindented/grunt-rcedit#3]
is there a way to change the language code using this? in the resource file there's:

```
BLOCK "VarFileInfo"
{
    VALUE "Translation", 0x0409 0x04B0
}
```

where 0x0409 is the English (United States)

need to change the language to my countries lang

**Comment by unindented** [comment]
`grunt-rcedit` is using `node-rcedit` under the covers, so their repo is probably the place to ask.

I'm looking at their source, and it looks like they are limited to these options for now: https://github.com/atom/node-rcedit/blob/f131746d1fa3019f8cb3490636311dec19b5da3a/src/rcedit.coffee#L4-L5
